---
title: "Example on how to load all datasets"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning=FALSE
  
)

library("tidyverse")
```

First you need to load the settings and the script with the loading functions:

```{r load_settings}
# Load project settings
source(here::here("settings.R"))
# Load helper functions
source(file.path(functions.dir, "output.R"))
```

Then you can load all datasets into different data.frames with the following code:

```{r load_data}
df.qpcr <- read_output_csv("qpcr", .output.dir = data.dir)
df.casy <- read_output_csv("casy", .output.dir = data.dir)
df.turbidostat <- read_output_csv("turbidostat", .output.dir = data.dir)
df.design <- read_output_csv("design", .output.dir = data.dir)
df.od <- read_output_csv("spectrophotometer", .output.dir = data.dir)
```

And take a look at each of them:

```{r}
glimpse(df.design)
```

```{r}
glimpse(df.qpcr)
```

```{r}
glimpse(df.casy)
```

```{r}
glimpse(df.turbidostat)
```

```{r}
glimpse(df.od)
```

