---
title: "Example on how to load all datasets"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning=FALSE
  
)
library("tidyverse")
```

First you need to load the settings and the script with the loading functions (you will need to have the `here`  package installed in your computer):

```{r load_settings}
# Load project settings
source(here::here("settings.R"))
# Load helper functions
source(file.path(functions.dir, "output.R"))
```

Then you can load all datasets into different data.frames with the following code:

```{r load_data}
df.counts.raw <- read_output_csv("raw_counts_transcriptomics", .output.dir = data.dir)
df.transcriptomics.design <- read_output_csv("transcriptomics_design", .output.dir = data.dir)
df.gene.id.matching <- read_output_csv("gene_id_matching", .output.dir = data.dir)
df.proteomics <- read_output_csv("proteomics", .output.dir = data.dir)
df.functional.categories <- read_output_csv("functional_categories", .output.dir = data.dir)
```

And take a look at each of them:

```{r}
glimpse(df.counts.raw)
```

```{r}
glimpse(df.transcriptomics.design)
```

```{r}
glimpse(df.gene.id.matching)
```

```{r}
glimpse(df.proteomics)
```

```{r}
glimpse(df.functional.categories)
```

